# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Deck.create(:title => 'ロジック・論理')
Deck.create(:title => 'エモーション・感情')
Deck.create(:title => 'グローバル')
Deck.create(:title => 'ドメスティック')
Deck.create(:title => 'リーダーシップ')
Deck.create(:title => 'フォロワーシップ')
Deck.create(:title => '挑戦')
Deck.create(:title => '安定')
Deck.create(:title => '変化')
Deck.create(:title => '一貫')
Deck.create(:title => '躍動的な人生')
Deck.create(:title => '平穏な人生')
Deck.create(:title => '自己成長')
Deck.create(:title => '貢献')
Deck.create(:title => '革新性')
Deck.create(:title => '創造性')
Deck.create(:title => '行動')
Deck.create(:title => '思考')
Deck.create(:title => '多様性')
Deck.create(:title => '一体感')
Deck.create(:title => '仕事')
Deck.create(:title => '家族')
Deck.create(:title => '情熱')
Deck.create(:title => '冷静')
Deck.create(:title => '忍耐力')
Deck.create(:title => '爆発力')
Deck.create(:title => 'ビジョン')
Deck.create(:title => '堅実')
Deck.create(:title => '謙虚')
Deck.create(:title => '尊敬')
Deck.create(:title => '信頼')
Deck.create(:title => '愛')
Deck.create(:title => '健康')
Deck.create(:title => 'プロフェショナル')
Deck.create(:title => 'シンプル')
Deck.create(:title => '努力')
Deck.create(:title => '感謝')
Deck.create(:title => '幸せ')
Deck.create(:title => '全力')
Deck.create(:title => '伝統')
Deck.create(:title => '友情')
Deck.create(:title => '影響力')
Deck.create(:title => '刺激')
Deck.create(:title => '誇り')
Deck.create(:title => '自由')
Deck.create(:title => '勝利')
Deck.create(:title => 'ポジティブ')
Deck.create(:title => '個性')
Deck.create(:title => '学習')
Deck.create(:title => '能力')
Deck.create(:title => '正直')
Deck.create(:title => '心地よさ')
Deck.create(:title => '遊び心')
Deck.create(:title => '効率')
Deck.create(:title => '気合い')
Deck.create(:title => '勇気')
Deck.create(:title => '喜び')
Deck.create(:title => '責任感')
Deck.create(:title => '最先端')
Deck.create(:title => '経験')
